[tool.poetry]
name = "llmonitor"
version = "0.0.35"
description = "Observability and monitoring for AI apps"
authors = ["llmonitor <hello@llmonitor.com>"]
readme = "README.md"
repository = "https://github.com/llmonitor/llmonitor-py/"
documentation = "https://llmonitor.com/docs/py/usage"
keywords = [
    "LLMonitor",
    "Langchain",
    "AI",
    "Analytics",
    "Monitoring"
]

[tool.poetry.dependencies]
python = "^3.8.1"
requests = "^2.31.0"
setuptools = "^68.2.2"
tenacity = "^8.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
